
modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"

[[mods]]
    modId="jeed"
    version="${file.jarVersion}"
    displayName="Just Enough Effect Descriptions"
    logoFile="icon.png"
    credits="MehVahdJukaar, Plantkillable"
    authors="MehVahdJukaar"
    itemIcon="minecraft:potion"
    description="A JEI plugin that displays all status effects and how to obtain them"

[[dependencies.jeed]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jeed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jeed]]
    modId="jei"
    mandatory=false
    versionRange="[13.1.0.2,)"
    ordering="NONE"
    side="CLIENT"
